import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({
  subsets: ["latin"],
});

function TopNav() {
  return (
    <div className="flex justify-between p-4 text-xl font-semibold">
      <div>Gallery</div>

      <div>Sign In</div>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable} `}>
      <body className={`font-sans ${inter.className} flex flex-col gap-4`}>
        <TopNav />
        {children}
      </body>
    </html>
  );
}
